apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8smanagement
  labels:
    app: k8smanagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8smanagement
  template:
    metadata:
      labels:
        app: k8smanagement
    spec:
      containers:
        - name: k8smanagement
          image: mo053/k8smanagement:0.0.1
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          env:
            - name: Production
              value: "True"
            - name: IsCluster
              value: "True"
          ports:
          - containerPort: 5000
      serviceAccount: cluster-management-sa
      serviceAccountName: cluster-management-sa
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "k8smanagement-svc"
  namespace: "yuuvis"
  labels:
    app: "k8smanagement"
spec:
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 5000
  selector:
    app: "k8smanagement"
  type: "ClusterIP"
