apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-info-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-info-role
rules:
- apiGroups: [""]
  resources: ["deployments", "services", "pods"]
  verbs: ["get", "list", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: service-reader-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-info-role
subjects:
- apiGroup: ""
  kind: ServiceAccount
  name: cluster-info-sa
  namespace: default