apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-management-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-management-role
rules:
- apiGroups: ["*"]
  resources: ["deployments", "services", "pods"]
  verbs: ["get", "list", "create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: service-reader-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-management-role
subjects:
- apiGroup: ""
  kind: ServiceAccount
  name: cluster-management-sa
  namespace: yuuvis